server:
  port: 0

kafka:
  brokers: localhost:59092

spring:
  application:
    name: kafka-producer
  datasource:
    url: jdbc:postgresql://localhost:5432/outbox
    username: postgres
    password: example
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop